#!/bin/bash -l
#PBS -l walltime=5:00:00
#PBS -l select=1:ncpus=4:mem=50G
#PBS -o outanderror
#PBS -e outanderror

cd $PBS_O_WORKDIR
mkdir -p "outanderror"
cd ../../
mkdir -p "$log_path"

module load r/4.0.3-foss-2020b

export MC_CORES=4
export OMP_NUM_THREADS=1

R CMD BATCH --slave ${path} $TMPDIR/log_${indexY}_${indexB}_${indexB1}_${indexD}_${PBS_ARRAY_INDEX}.log
cp $TMPDIR/log_${indexY}_${indexB}_${indexB1}_${indexD}_${PBS_ARRAY_INDEX}.log ${log_path}
